FROM golang:1.19 as builder
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /build-dir
ADD ./go.mod ./go.mod
ADD ./go.sum ./go.sum
RUN go mod download
ADD . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o controller-server cmd/controller/main.go

FROM alpine
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /build-dir/controller-server /controller-server
ENTRYPOINT ["/controller-server"]
